<a href="https://colab.research.google.com/github/edgi-govdata-archiving/EEW-ICE/blob/main/ICE_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#This notebook is intended to analyze
#exposure to environmental hazards at ICE facilities

#First, do exposures to SDWA violations differ for
#populations with children vs those that are only adults?

#No AI was used in the development of this notebook

In [1]:
import pandas as pd
import geopandas as gpd

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [17]:
sheet_id = "1C8Ip6Nq9FocXcNIQnyjGxHxVoOLYaHmBmjOepwB2lxw"
sheet_name = "ddp"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&amp;sheet={sheet_name}"
data = pd.read_csv(url)

#referenced: https://towardsdatascience.com/read-data-from-google-sheets-into-pandas-without-the-google-sheets-api-5c468536550/

In [3]:
w_children = data[data["under_18_num"]==1]
w_children

,Unnamed: 0.1,index_left,PWSID,PWS_Name,LOCATION_CONFIDENCE,PRIMACY_AGENCY_CODE,PWS_TYPE_CODE_x,POPULATION_SERVED_COUNT_x,PRIMARY_SOURCE_CODE_x,IS_WHOLESALER_IND,...,Confirmed,PWSID_1,Shape_Length,Shape_Area,Date_Create,PWS_TYPE_CODE,PRIMARY_SOURCE_CODE,POPULATION_SERVED_COUNT,Unnamed: 828,Unnamed: 829
19,33,22129,GA1210001,ATLANTA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,382618.55280,1.456211e+09,NaN,CWS,SW,1089893.0,NaN,NaN
37,59,36522,MA3048000,BURLINGTON WATER DEPT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,36282.14508,5.152135e+07,2020-01-01,CWS,SW,25864.0,NaN,NaN
48,72,31662,NY1400443,ECWA DIRECT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,380806.03680,7.060543e+08,NaN,CWS,SW,313380.0,NaN,NaN
51,75,38128,IL0316000,CHICAGO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,395495.52590,1.078280e+09,2025-08-19,CWS,SW,2721308.0,NaN,NaN
66,96,6201,AZ0411017,FLORENCE WATER COMPANY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29327.96392,1.403824e+07,2021-09-09,CWS,GW,15900.0,NaN,NaN
86,124,25694,IN5211001,BRAZIL CITY WATER WORKS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45200.23284,3.925832e+07,2024-06-06,CWS,GW,12000.0,NaN,NaN
97,138,9935,TX2400001,CITY OF LAREDO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,223920.55920,1.342824e+09,2023-01-12,CWS,SW,260046.0,NaN,NaN
109,154,12519,TX0570004,DALLAS WATER UTILITY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,342819.74640,1.250921e+09,2024-04-09,CWS,SW,1356479.0,NaN,NaN
114,160,33921,NJ0714001,NEWARK WATER DEPARTMENT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,79003.95202,1.441925e+08,2015-10-20,CWS,SW,294274.0,NaN,NaN
117,164,38841,CO0203002,ARAPAHOE CNTY WWWA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,71939.62914,4.985453e+07,2023-10-26,CWS,GW,31000.0,NaN,NaN
126,176,9973,TX1620001,CITY OF EAGLE PASS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,135367.74680,1.172020e+08,2020-05-04,CWS,SW,54900.0,NaN,NaN
137,190,7140,TX0710002,EL PASO WATER UTILITIES PUBLIC SERVICE B,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,333662.65810,1.044584e+09,2024-03-01,CWS,SW,747168.0,NaN,NaN
141,194,7162,TX0710020,FORT BLISS MAIN POST AREA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,174092.81900,6.146252e+08,2024-04-09,CWS,GW,28000.0,NaN,NaN
153,210,22129,GA1210001,ATLANTA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,382618.55280,1.456211e+09,NaN,CWS,SW,1089893.0,NaN,NaN
160,218,6201,AZ0411017,FLORENCE WATER COMPANY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29327.96392,1.403824e+07,2021-09-09,CWS,GW,15900.0,NaN,NaN
161,219,6201,AZ0411017,FLORENCE WATER COMPANY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29327.96392,1.403824e+07,2021-09-09,CWS,GW,15900.0,NaN,NaN
162,220,43665,GA1150002,ROME,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,269238.56270,1.658014e+08,NaN,CWS,SW,45586.0,NaN,NaN
176,238,5028,CA1510013,"MCFARLAND, CITY OF",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,15658.13647,8.284339e+06,2020-10-20,CWS,GW,14161.0,NaN,NaN
200,276,12665,TX1010013,CITY OF HOUSTON,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,987479.13860,1.969721e+09,2023-10-11,CWS,SW,2970543.0,NaN,NaN
204,282,5388,CA1310004,"EL CENTRO, CITY OF",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,30976.79145,3.354074e+07,2020-10-20,CWS,SWP,43772.0,NaN,NaN
209,289,38131,FL2161328,JEA MAJOR GRID,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,501844.43030,2.281102e+09,2025-08-19,CWS,GW,826664.0,NaN,NaN
215,297,9847,TX1280007,EL OSO WSC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,443332.47810,1.733280e+09,2024-04-09,CWS,GW,6288.0,NaN,NaN
250,345,4567,CA1910067,"LOS ANGELES-CITY, DEPT. OF WATER & POWER",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,530410.29940,1.878881e+09,2023-12-21,CWS,SW,3875566.0,NaN,NaN
266,366,19729,TN0000450,"MEMPHIS LIGHT, GAS, & WATER",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,443836.87340,2.658736e+09,2023-11-29,CWS,GW,659500.0,NaN,NaN
284,395,13146,TX1700001,CITY OF CONROE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,198898.86470,2.493311e+08,2024-03-19,CWS,SWP,113912.0,NaN,NaN
286,401,34107,NY7003493,NEW YORK CITY SYSTEM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,628819.37700,1.341559e+09,NaN,CWS,SW,8271000.0,NaN,NaN
309,431,27930,FL3480962,ORLANDO UTILITIES COMMISSION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,263301.78490,6.640137e+08,2022-02-21,CWS,GW,536466.0,NaN,NaN
311,433,5290,CA3710034,OTAY WATER DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,247767.01330,4.542677e+08,2023-10-21,CWS,SWP,238008.0,NaN,NaN
319,451,5463,AZ0407025,PHOENIX CITY OF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,355583.44280,2.035335e+09,2021-09-09,CWS,SW,1695000.0,NaN,NaN
326,459,14145,LA1039018,PINE PRAIRIE CORRECTIONAL FACILITY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,51078.89606,4.454003e+07,2024-06-06,CWS,GW,900.0,NaN,NaN
328,461,31166,PA5020038,PITTSBURGH WATER & SEWER AUTH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,149777.28040,1.712271e+08,2021-03-30,CWS,SW,520000.0,NaN,NaN
334,468,11002,TX0310096,EAST RIO HONDO WSC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,339005.63400,1.149220e+09,2024-05-01,CWS,SW,24756.0,NaN,NaN
340,474,11514,TX1260018,JOHNSON COUNTY SUD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,614469.75610,1.118956e+09,2023-01-20,CWS,SWP,65517.0,NaN,NaN
351,492,9934,TX2400022,WEBB COUNTY WATER UTILITIES,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,117785.08470,2.939980e+08,2024-04-12,CWS,SW,8358.0,NaN,NaN
352,494,11002,TX0310096,EAST RIO HONDO WSC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,339005.63400,1.149220e+09,2024-05-01,CWS,SW,24756.0,NaN,NaN
356,499,40917,GA0630000,CLAYTON COUNTY WATER AUTHORITY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,166208.60480,6.757224e+08,2025-10-01,CWS,SW,298374.0,NaN,NaN
362,506,35619,VT0005130,ST ALBANS WATER DEPT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,49090.35724,4.046146e+07,2024-06-06,CWS,SW,10200.0,NaN,NaN
366,511,9883,TX0150018,SAN ANTONIO WATER SYSTEM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,776031.29990,3.081115e+09,2023-02-07,CWS,SWP,2643729.0,NaN,NaN
370,515,41297,PR0002591,METROPOLITANO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,143390.73170,1.361927e+08,NaN,CWS,SW,1084637.0,NaN,NaN
372,517,5105,CA3010038,CITY OF SANTA ANA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,59809.40036,1.029810e+08,2020-10-20,CWS,SWP,310539.0,NaN,NaN
373,518,1478,CA4210011,CITY OF SANTA MARIA UTILITIES DEPARTMENT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,61491.33404,7.374080e+07,2020-10-20,CWS,SWP,109477.0,NaN,NaN
381,526,4378,WA5341998,KING COUNTY WATER DISTRICT #125,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,36645.38154,2.740088e+07,2016-06-29,CWS,SWP,21904.0,NaN,NaN
385,530,412,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,110671.33660,1.917318e+08,2020-10-20,CWS,SWP,848019.0,NaN,NaN
387,534,5292,CA3710020,"SAN DIEGO, CITY OF",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,302511.49220,9.649569e+08,2023-08-26,CWS,SW,1385379.0,NaN,NaN
391,538,9929,TX0820001,CITY OF DILLEY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38451.24915,1.430690e+07,1963-01-01,CWS,GW,4505.0,NaN,NaN
392,539,9930,TX0820002,CITY OF PEARSALL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,32360.03531,2.013203e+07,2020-05-06,CWS,GW,8985.0,NaN,NaN
414,579,6192,AZ0410112,TUCSON CITY OF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,778219.89950,1.364652e+09,2021-09-09,CWS,GW,732906.0,NaN,NaN

In [4]:
adult_only = data[data["under_18_num"]==0]
adult_only

,Unnamed: 0.1,index_left,PWSID,PWS_Name,LOCATION_CONFIDENCE,PRIMACY_AGENCY_CODE,PWS_TYPE_CODE_x,POPULATION_SERVED_COUNT_x,PRIMARY_SOURCE_CODE_x,IS_WHOLESALER_IND,...,Confirmed,PWSID_1,Shape_Length,Shape_Area,Date_Create,PWS_TYPE_CODE,PRIMARY_SOURCE_CODE,POPULATION_SERVED_COUNT,Unnamed: 828,Unnamed: 829
0,1,58090,VA6033515,PEUMANSEND CREEK REGIONAL JAIL,HIGHER,VA,NTNCWS,396.0,GW,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,45466,MT0004789,MT AIR NATL GUARD 120TH AIR LIFT WING,HIGHER,MT,NTNCWS,350.0,SWP,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,7541,MN5340259,Kandiyohi County Emergency Management,LOWER,MN,TNCWS,25.0,GW,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,6534,AZ0407095,MESA CITY OF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,204539.818900,5.404696e+08,2021-09-09,CWS,SW,466000.0,NaN,NaN
4,12,32841,PA3060127,ABRAXAS ACADEMY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,814.488932,4.063992e+04,NaN,CWS,GW,156.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,645,3993,WA5399150,YAKIMA WATER DIVISION CITY OF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,102058.504300,1.022135e+08,2016-11-02,CWS,SW,112858.0,NaN,NaN
451,646,9704,MT0000153,BILLINGS CITY OF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,273085.152700,2.104310e+08,NaN,CWS,SW,114000.0,NaN,NaN
452,647,41324,SC4610001,YORK CITY OF (SC4610001),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,66112.951640,1.004123e+08,NaN,CWS,SWP,11137.0,NaN,NaN
453,648,31411,PA7670100,YORK WATER CO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,521985.945200,1.333181e+09,2018-06-27,CWS,SW,206762.0,NaN,NaN
454,649,31411,PA7670100,YORK WATER CO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,521985.945200,1.333181e+09,2018-06-27,CWS,SW,206762.0,NaN,NaN

In [5]:
pd.set_option('display.float_format', lambda x: '%.5f' % x) #consulted: https://stackoverflow.com/questions/55394854/how-to-change-the-format-of-describe-output

In [6]:
w_children["proximity.npdes"].describe()

count       47.00000
mean      7793.22671
std      26625.76217
min          0.00000
25%         12.41460
50%         72.96550
75%       1497.37560
max     156080.75140
Name: proximity.npdes, dtype: float64

In [7]:
adult_only["proximity.npdes"].describe()

count       396.00000
mean      21215.84381
std      216204.61035
min           0.00000
25%           1.57475
50%          57.11520
75%        1077.63153
max     4029836.75500
Name: proximity.npdes, dtype: float64

In [8]:
data["proximity.npdes"].describe()

count       443.00000
mean      19791.77382
std      204608.83950
min           0.00000
25%           1.76740
50%          59.42910
75%        1118.50230
max     4029836.75500
Name: proximity.npdes, dtype: float64

In [9]:
w_children["VIOREMAIN"].describe()

count   47.00000
mean     2.91489
std      9.48644
min      0.00000
25%      0.00000
50%      0.00000
75%      1.00000
max     61.00000
Name: VIOREMAIN, dtype: float64

In [10]:
adult_only["VIOREMAIN"].describe()

count   407.00000
mean      1.89681
std       8.10578
min       0.00000
25%       0.00000
50%       0.00000
75%       1.00000
max      96.00000
Name: VIOREMAIN, dtype: float64

In [11]:
data["VIOREMAIN"].describe()

count   454.00000
mean      2.00220
std       8.25357
min       0.00000
25%       0.00000
50%       0.00000
75%       1.00000
max      96.00000
Name: VIOREMAIN, dtype: float64

In [12]:
w_children["num_waterdis"].describe()

count     47.00000
mean     180.74468
std      251.50038
min        2.50000
25%       25.75000
50%       82.30000
75%      232.15000
max     1163.10000
Name: num_waterdis, dtype: float64

In [13]:
adult_only["num_waterdis"].describe()

count   406.00000
mean    119.71502
std     159.06651
min       0.20000
25%      21.60000
50%      60.20000
75%     141.67500
max     948.30000
Name: num_waterdis, dtype: float64

In [14]:
data["num_waterdis"].describe()

count    453.00000
mean     126.04702
std      171.62600
min        0.20000
25%       22.40000
50%       60.40000
75%      148.10000
max     1163.10000
Name: num_waterdis, dtype: float64

In [16]:
sheet_id = "1XCCAycaU9Y0gJva2Ef9I6NxqEnQWXvwitHjJsmLu7jo"
sheet_name = "ice_gov"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&amp;sheet={sheet_name}"
data_ice = pd.read_csv(url)

#referenced: https://towardsdatascience.com/read-data-from-google-sheets-into-pandas-without-the-google-sheets-api-5c468536550/

In [18]:
ice_w_children = data_ice[data_ice["under_18_num"]==1]

In [20]:
ice_adult = data_ice[data_ice["under_18_num"]==0]

In [21]:
ice_w_children["proximity.npdes"].describe()

count     15.00000
mean     511.85913
std      966.42549
min        0.00000
25%        0.65725
50%       22.15290
75%      320.61840
max     2942.01330
Name: proximity.npdes, dtype: float64

In [22]:
ice_adult["proximity.npdes"].describe()

count       82.00000
mean      4376.42269
std      24574.17617
min          0.00000
25%          0.69403
50%         16.54800
75%        520.48715
max     219319.48300
Name: proximity.npdes, dtype: float64

In [23]:
data_ice["proximity.npdes"].describe()

count       97.00000
mean      3778.80977
std      22619.48751
min          0.00000
25%          0.68610
50%         16.60300
75%        496.51160
max     219319.48300
Name: proximity.npdes, dtype: float64

In [24]:
ice_w_children["VIOREMAIN"].describe()

count   15.00000
mean     6.73333
std     16.12658
min      0.00000
25%      0.00000
50%      1.00000
75%      2.50000
max     61.00000
Name: VIOREMAIN, dtype: float64

In [25]:
ice_adult["VIOREMAIN"].describe()

count   84.00000
mean     1.78571
std      7.10518
min      0.00000
25%      0.00000
50%      0.00000
75%      1.00000
max     61.00000
Name: VIOREMAIN, dtype: float64

In [26]:
data_ice["VIOREMAIN"].describe()

count   99.00000
mean     2.53535
std      9.11526
min      0.00000
25%      0.00000
50%      0.00000
75%      1.00000
max     61.00000
Name: VIOREMAIN, dtype: float64

In [28]:
ice_w_children["num_waterdis"].describe()

count    15.00000
mean    107.12667
std     198.57998
min       2.50000
25%      14.40000
50%      26.40000
75%      68.10000
max     760.40000
Name: num_waterdis, dtype: float64

In [29]:
ice_adult["num_waterdis"].describe()

count    83.00000
mean     90.46627
std     138.79514
min       0.20000
25%       6.80000
50%      30.80000
75%     120.80000
max     680.40000
Name: num_waterdis, dtype: float64

In [27]:
data_ice["num_waterdis"].describe()

count    98.00000
mean     93.01633
std     148.36767
min       0.20000
25%       7.50000
50%      29.95000
75%     117.57500
max     760.40000
Name: num_waterdis, dtype: float64